import { APIGatewayProxyEvent } from "aws-lambda";

export const createMockEvent = (path: string, method: string, body: string): APIGatewayProxyEvent => {
    return {
        body: body,
        headers: {},
        multiValueHeaders: {},
        httpMethod: method,
        isBase64Encoded: false,
        path: path,
        pathParameters: null,
        queryStringParameters: null,
        multiValueQueryStringParameters: null,
        stageVariables: null,
        resource: "/{proxy+}",
        requestContext: {
            accountId: "123456789012",
            apiId: "api-id",
            authorizer: undefined,
            protocol: "HTTP/1.1",
            httpMethod: "GET",
            identity: {
            accessKey: null,
            accountId: null,
            apiKey: null,
            apiKeyId: null,
            caller: null,
            clientCert: null,
            cognitoAuthenticationProvider: null,
            cognitoAuthenticationType: null,
            cognitoIdentityId: null,
            cognitoIdentityPoolId: null,
            principalOrgId: null,
            sourceIp: "127.0.0.1",
            user: null,
            userAgent: "Custom User Agent String",
            userArn: null,
            },
            path: "/test",
            stage: "dev",
            requestId: "id",
            requestTimeEpoch: Date.now(),
            resourceId: "resource-id",
            resourcePath: "/{proxy+}",
        },
    };
}
